### ISSUE TITLE
Convert RLIS taxlot data to single table (if possible)

### ISSUE THREAD

**Issue by nickembrey** [hackoregon/2019-housing-backend#16]
We should try to convert the RLIS taxlot data from its file geodatabase format into a single SQL table.

**Comment by nickembrey** [comment]
Doing this is complicated by some of the various layers/features in the GDB-form RLIS taxlot data having slightly different specifications. I'm going to leave this ticket open because I think this would still be a valuable change toward making the data more accessible, but it might take more familiarity with the data than I have to decide how to proceed.

**Comment by znmeb** [comment]
You should be able to import a GDB directly to PostgreSQL with `ogr2ogr` as long as no individual table has no more columns that the PostgreSQL limit.

**Comment by nickembrey** [comment]
I should have been more clear when I wrote this issue: we did import the GDB into Postgres using `ogr2ogr` last year but the GDB has a "feature" for each year that is imported into Postgres as a separate table. These data would be a little more accessible if they were available in a single table with a "year" column, but since different years have different specifications it is slightly complicated. We would need to do a crosswalk for the various years/features and collate them accordingly.

**Comment by znmeb** [comment]
Ah ... OK. That makes it an SQL exercise rather than `ogr2ogr`. My guess is the path of least resistance is to code it into the Django REST Framework API; you'd have a uniform interface presented to the front end without having to mess with the existing database.

But you should probably close this `wontfix` until we know what's up for the season.
