### ISSUE TITLE
Create materialized views for HMDA data

### ISSUE THREAD

**Issue by nickembrey** [hackoregon/2019-housing-backend#7]
We should create materialized views to store Postgres queries for the HMDA data to reduce latency once we know what queries we will be making against the database.

**Comment by znmeb** [comment]
Materialized views don't have primary keys - that might mess up the API.

**Comment by nickembrey** [comment]
Yeah, I closed this ticket because I don't think this is necessarily the way forward. One idea for handling this very large database: maybe we segregate the data on some variable into several tables and switch between those tables in the API endpoint?

**Comment by znmeb** [comment]
Save the issue for our sandbox "opportunity project" - we're doing some scalability work as part of that. I don't remember if we're planning on using this dataset but I think we are.

**Comment by nickembrey** [comment]
Okay, cool, thanks for the info! Where can I track that project or put a note about this issue attached to that project?

**Comment by znmeb** [comment]
We don't have a project tracker yet. I'll let you know when we have a place for it.

**Comment by nickembrey** [comment]
Okay, thanks Ed!
