### ISSUE TITLE
Supplement NCDB data

### ISSUE THREAD

**Issue by nickembrey** [hackoregon/2019-housing-backend#9]
We now have full yearly population counts and corresponding census tract geocode. We need to supplement our current dataset with this additional data with some migrations.

https://slack-files.com/TEW0B5TPE-FKEBWDDBN-b04f454303

**Comment by nickembrey** [comment]
Should all be in the database now. Just need to add migrations to the repo.

**Comment by maryannet** [comment]
transportation has the ncdb opportunity zones data
